exports.classes = [
    "English 9",
    "English 10",
    "English 11: Global Literacies",
    "English 11: AP Language",
    "English 12: AP Literature",
    "English 12: Advanced Journalism",
    "English 12: Debate",
    "English 12: Literary Analysis",
    "English 12: Mulitliteracies",
    "English 12: Senior Composition",
    "English 12: Speech and Interpersonal Communications",
    "Debate",
    "Journalism I",
    "Journalism II",
    "ESL Intermediate",
    "ESL Advanced",
    "Acting I",
    "Advanced Acting",
    "Advanced Studio Art",
    "AP Art History",
    "AP Music Theory",
    "Choir",
    "Directing",
    "Electronic Music Ensemble",
    "Intermediate Ceramics",
    "Orchestra",
    "Photography",
    "Piano I",
    "2D Studio: Drawing, Painting, and Printmaking",
    "Yearbook: Publications",
    "Ceramics I",
    "Electronic Music I",
    "Foundations in Visual Art",
    "Glass I",
    "Public Speaking",
    "Sculpture",
    "Theater Technology I",
    "Woodworking I",
    "Writing for Performance",
    "Advanced Music Production",
    "Ceramics II",
    "Glass II",
    "Introductory Printmaking",
    "Theater Technology II",
    "Woodworking II",
    "Arts Concentration",
    "Global Concentration: Cohort",
    "Global Concentration: Capstone",
    "The Art of Disagreement",
    "The Good Life: An Exploration and Study of Global Happiness",
    "World History I",
    "World History II",
    "AP World History",
    "U. S. History",
    "AP U.S. History",
    "AP Economics",
    "AP United States and Comparative Government and Politics",
    "A History of Human Rights in the Americas",
    "Introductory Economics",
    "Philosophy: Freedom, Order and Society",
    "A History of Global Human Rights",
    "Blood and Sugar: History of Cuba",
    "Entrepreneurship",
    "Algebra I",
    "Geometry",
    "Geometry Advanced",
    "Conceptual Algebra II",
    "Algebra II",
    "Algebra II/Precalculus Advanced (APA)",
    "Conceptual Precalculus",
    "Discrete Math with Applications",
    "Precalculus",
    "Calculus",
    "AP Calculus AB",
    "AP Calculus BC",
    "AP Statistics",
    "Formal Logic",
    "Multivariable Calculus",
    "Web Development",
    "AP Computer Science Principles",
    "AP Computer Science A",
    "Chinese I",
    "Chinese II",
    "Chinese III",
    "Chinese IV",
    "AP Chinese Language and Culture",
    "Chinese Cultural Studies: Contemporary Society (PAP)",
    "French I",
    "French II",
    "French III",
    "French IV Advanced",
    "AP French Language and Culture",
    "Spanish I",
    "Spanish II",
    "Spanish III",
    "Spanish IV Advanced",
    "Heritage Spanish: Nuestra identidad global",
    "AP Spanish Literature and Culture",
    "Contemporary Civilization and Culture of Latin America (PAP)",
    "Le Monde Francophone (The French-speaking world) (PAP)",
    "Advanced Topics in Linguistics: French Phonetics",
    "Conversación y cultura del mundo hispano (Conversation and Culture of the Hispanic World)",
    "Advanced Topics in Communication: French Conversation",
    "Temas actuales del mundo hispano (Current Events of the Hispanic World)",
    "Latin I",
    "Latin II",
    "Latin III",
    "Latin IV Advanced",
    "Biology I",
    "Advanced Biology",
    "AP Biology",
    "Bioengineering Research & Design",
    "Chemistry I",
    "Advanced Chemistry",
    "AP Chemistry",
    "AP Environmental Science",
    "Physics I",
    "Advanced Physics",
    "AP Physics C Mechanics",
    "AP Physics C Electricity and Magnetism",
    "Principles of Engineering",
    "Biochemistry Research I",
    "Biochemistry Research II",
    "AP Psychology",
    "Adolescent Psychology",
    "Anatomy and Physiology: Foundations",
    "Introduction to Astronomy",
    "Forensic Science: Modern Cases",
    "Anatomy and Physiology: Advanced Systems",
    "Introduction to Natural Disasters",
    "Forensic Science: Modern Cases",
    "Health, Wellness, and Community: 9",
    "Health, Wellness, and Community: 10",
    "Health, Wellness, and Community: 11",
    "Health, Wellness, and Community: 12",
];